version: 1.0.{build}
image: Visual Studio 2019
shallow_clone: true
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
cache: packages
build_script:
- cmd: build.cmd
on_failure:
- cmd: >-
    pwd

    type build.cmd

    tree /f >FailedBuild-Files.listing

    appveyor PushArtifact FailedBuild-Files.listing